### ISSUE TITLE
Typo in ReadMe

### ISSUE THREAD

**Issue by hristodobrev** [n0n3br/RxJsStore#2]
Hi,

Just noticed a typo in the ReadMe.

The following line has one of the brackets missplaced:
https://github.com/n0n3br/RxJsStore/blob/1192ccc9e9bce8f77fd8ffe991354bddd9fd88bb/README.md?plain=1#L81

It should be:
() => new Promise((resolve) => setTimeout(() => resolve(5), 1000))

**Comment by n0n3br** [comment]
Ok, thanks for the alert. Fixed. You could have done a pull request too if you wanted to.
